export const EDIT_TASK_REQUESTED = 'EDIT_TASK_REQUESTED';
export const EDIT_TASK_SUCCEEDED = 'EDIT_TASK_SUCCEEDED';
export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED';
export const EDIT_TASK_MODAL = 'EDIT_TASK_MODAL';
