export const ADD_TASK_REQUESTED = 'ADD_TASK_REQUESTED';
export const ADD_TASK_SUCCEEDED = 'ADD_TASK_SUCCEEDED';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const EDIT_TASK_REQUESTED = 'EDIT_TASK_REQUESTED';
export const EDIT_TASK_SUCCEEDED = 'EDIT_TASK_SUCCEEDED';
export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED';
export const EDIT_TASK_MODAL = 'EDIT_TASK_MODAL';

export const HANDLE_ADDTASK_FORM = 'HANDLE_ADDTASK_FORM';
export const SET_ADDTASK_MODAL = 'SET_ADDTASK_MODAL';
