export const GET_ALL_LISTS = 'GET_ALL_LISTS';
export const GET_ALL_LISTS_FAIL = 'GET_ALL_LISTS_FAIL';
export const GET_ALL_LISTS_SUCCEEDED = 'GET_ALL_LISTS_SUCCEEDED';
export const GET_ALL_LISTS_REQUESTED = 'GET_ALL_LISTS_REQUESTED';
